##############################################################
# +--------------------------------------------------------+ #
# |                      Lobby plugin                      | #
# +                      config.yml                        + #
# |                  Created by Matzuake                   | #
# +--------------------------------------------------------+ #
##############################################################


############################################################
# +------------------------------------------------------+ #
# |                         Prefix                       | #
# +------------------------------------------------------+ #
############################################################
Prefix:
  IngamePrefix: '&7[&6Lobby&7] '
  ConsolenPrefix: '&7[&6Lobby&7] '

############################################################
# +------------------------------------------------------+ #
# |                     Rechte Nachrichten               | #
# +------------------------------------------------------+ #
############################################################
Rechte:
  Console: '&cDie Console darf das leider nicht!'

############################################################
# +------------------------------------------------------+ #
# |                          DatenSchutz                 | #
# |                          & Settings                  | #
# +------------------------------------------------------+ #
############################################################
Datenschutz:
  Datenlink: '&4https://letsplaymc.net/datenschutz.html'

############################################################
# +------------------------------------------------------+ #
# |                     Inventar Items                   | #
# +------------------------------------------------------+ #
############################################################
Items:
  Navigator: 'COMPASS'
  Navigator_Platz: 0
  PlayerHide: 'BLAZE_POWDER'
  PlayerHide_Platz: 3
  Datenschutz: 'enchanted_book'
  Datenschutz_on: 'WOOL'
  Datenschutz_off: 'WOOL'


